name: v_chat_sdk
repository: https://github.com/hatemragab/v_chat_sdk

packages:
  - core_packages/**
  - v_ui_packages/**
  - push_providers/**
  - v_shared_packages/**
ignore:
  - 'core_packages/v_chat_utils/utils_example'
  - 'v_shared_packages/v_chat_input_ui/input_example'
  - 'v_shared_packages/v_chat_media_editor/editor_example'
  - 'v_shared_packages/v_chat_receive_share/receive_share_example'
  - 'v_shared_packages/v_chat_voice_player/voice_example'
  - 'v_ui_packages/v_chat_message_page/message_example'
  - 'v_ui_packages/v_chat_room_page/room_example'
  - 'v_ui_packages/v_chat_web_rtc/rtc_example'

command:
#  version:
#    # Generate commit links in package changelogs.
#    linkToCommits: true
#    # # Only allow versioning to happen on main branch.
#    # branch: master
#    # Additionally build a changelog at the root of the workspace.
#    workspaceChangelog: true
#    changelogs:
#      - path: x.md
#        description: |
#          All notable changes for vchatsdk packages
  bootstrap:
    runPubGetInParallel: true
    usePubspecOverrides: true

scripts:
  format:
    run: melos exec -c 1 -- \
      flutter format .
  fix:
    run: melos exec -c 1 -- \
      dart fix --apply
  add:
    run: melos exec -c 1 -- \
      flutter pub add flutter_lints --dev
  g:
    run: cd core_packages/v_chat_sdk_core && flutter pub run build_runner build --delete-conflicting-outputs
  add-license-header:
    # If you add here another --ignore flag, add it also to
    # "check-license-header".
    run: |
      addlicense -f header_template.txt \
        --ignore "**/*.yml" \
        --ignore "**/*.yaml" \
        --ignore "**/*.xml" \
        --ignore "**/*.g.dart" \
        --ignore "**/*.sh" \
        --ignore "**/*.html" \
        --ignore "**/*.js" \
        --ignore "**/*.ts" \
        --ignore "**/*.g.h" \
        --ignore "**/*.g.m" \
        --ignore "**/*.rb" \
        --ignore "**/*.txt" \
        --ignore "**/*.cmake" \
        --ignore "**/Runner/AppDelegate.swift" \
        --ignore "**/Runner/MainFlutterWindow.swift" \
        --ignore "**/Runner/Runner-Bridging-Header.h" \
        --ignore "**/Runner/AppDelegate.h" \
        --ignore "**/Runner/AppDelegate.m" \
        --ignore "**/Runner/main.m" \
        --ignore "**/MainActivity.kt" \
        --ignore "**/MainActivity.java" \
        --ignore "**/FlutterMultiDexApplication.java" \
        --ignore "**/GeneratedPluginRegistrant.swift" \
        --ignore "**/Pods/**" \
        --ignore "**/flutter/generated_plugin_registrant.h" \
        --ignore "**/flutter/generated_plugin_registrant.cc" \
        .
    description: Add a license header to all necessary files.
  check-license-header:
    # If you add here another --ignore flag, add it also to
    # "add-license-header".
    run: |
      addlicense -f header_template.txt \
        --check \
        --ignore "**/*.yml" \
        --ignore "**/*.yaml" \
        --ignore "**/*.xml" \
        --ignore "**/*.g.dart" \
        --ignore "**/*.sh" \
        --ignore "**/*.html" \
        --ignore "**/*.js" \
        --ignore "**/*.ts" \
        --ignore "**/*.g.h" \
        --ignore "**/*.g.m" \
        --ignore "**/*.rb" \
        --ignore "**/*.txt" \
        --ignore "**/*.cmake" \
        --ignore "**/Runner/AppDelegate.swift" \
        --ignore "**/Runner/MainFlutterWindow.swift" \
        --ignore "**/Runner/Runner-Bridging-Header.h" \
        --ignore "**/Runner/AppDelegate.h" \
        --ignore "**/Runner/AppDelegate.m" \
        --ignore "**/Runner/main.m" \
        --ignore "**/MainActivity.kt" \
        --ignore "**/MainActivity.java" \
        --ignore "**/FlutterMultiDexApplication.java" \
        --ignore "**/GeneratedPluginRegistrant.swift" \
        --ignore "**/Pods/**" \
        --ignore "**/flutter/generated_plugin_registrant.h" \
        --ignore "**/flutter/generated_plugin_registrant.cc" \
        .
    description: Add a license header to all necessary files.