name: v_chat_receive_share
description: v chat receive share will make your app support share from other apps
version: 2.1.0
homepage: https://v-chat-sdk.github.io/vchat-v2-docs/docs/intro
issue_tracker: https://github.com/hatemragab/v_chat_sdk/issues
repository: https://github.com/hatemragab/v_chat_sdk/tree/master/v_shared_packages/v_chat_receive_share

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  v_chat_sdk_core: ^2.1.0
  share_handler: ^0.0.21
  v_chat_media_editor: ^2.0.0
  v_platform: ^2.0.0
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lints: ^4.0.0


flutter:

platforms:
  android:
  ios:
  web:
  windows:
  macos:
