// Copyright 2023, the hatemragab project author.
// All rights reserved. Use of this source code is governed by a
// MIT license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqYkVdzjKcDE8l_PuSKFGcMlTRaS4IZS8',
    appId: '1:706118575283:web:b556808062b0ee5eb8bcc6',
    messagingSenderId: '706118575283',
    projectId: 'v-chat-sdk-v2',
    authDomain: 'v-chat-sdk-v2.firebaseapp.com',
    storageBucket: 'v-chat-sdk-v2.appspot.com',
    measurementId: 'G-VEWQSFXB6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFRPlt74bHykCcSukkeAU5gLRiASR6mTk',
    appId: '1:706118575283:android:d5f6b83d3debde31b8bcc6',
    messagingSenderId: '706118575283',
    projectId: 'v-chat-sdk-v2',
    storageBucket: 'v-chat-sdk-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPF9x4otICpjEYAOdGeHJWyxiZHlSExpI',
    appId: '1:706118575283:ios:17e133cae0c891d7b8bcc6',
    messagingSenderId: '706118575283',
    projectId: 'v-chat-sdk-v2',
    storageBucket: 'v-chat-sdk-v2.appspot.com',
    iosClientId:
        '706118575283-36suf2ucff8cdel98n6rpc9o81cqj1n4.apps.googleusercontent.com',
    iosBundleId: 'com.vchatsdk.app.v2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPF9x4otICpjEYAOdGeHJWyxiZHlSExpI',
    appId: '1:706118575283:ios:17e133cae0c891d7b8bcc6',
    messagingSenderId: '706118575283',
    projectId: 'v-chat-sdk-v2',
    storageBucket: 'v-chat-sdk-v2.appspot.com',
    iosClientId:
        '706118575283-36suf2ucff8cdel98n6rpc9o81cqj1n4.apps.googleusercontent.com',
    iosBundleId: 'com.vchatsdk.app.v2',
  );
}
